/**
 * Chat Socket.IO Handler
 *
 * Real-time events for:
 *  - New lead notifications to suppliers (lead:new)
 *  - Buyer-supplier chat in inquiry threads (chat:message, chat:typing, chat:read)
 *
 * Auth:
 *  - Suppliers: JWT in `auth.token` (same token used for REST API)
 *  - Buyers: HMAC token in `auth.buyerToken` + `auth.email` (generated by /api/chat/:inquiryId/token)
 *
 * Rooms:
 *  - `supplier:<supplierId>` -- joined automatically on supplier auth; receives lead:new
 *  - `inquiry:<inquiryId>` -- joined by either party when viewing a chat thread
 *
 * Setup:
 *  - Imported in server.ts after http server is created
 *  - Initialized once: `initSocket(httpServer)`
 *  - Use `getIO()` anywhere else to emit events
 */

import { Server as HttpServer } from 'http';
import { Server as IOServer, Socket } from 'socket.io';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import { verifyToken } from '../utils/jwt';
import { generateBuyerToken } from '../controllers/chatController';

const CHAT_SECRET = process.env.CHAT_SECRET || 'ritzyard-chat-secret-2025';

let io: IOServer | null = null;

interface AuthedSocket extends Socket {
  data: {
    role?: 'supplier' | 'buyer' | 'admin';
    supplierId?: string;
    email?: string;
  };
}

/**
 * Initialize the Socket.IO server bound to the given HTTP server.
 * Idempotent: calling twice is a no-op.
 */
export function initSocket(httpServer: HttpServer): IOServer {
  if (io) return io;

  io = new IOServer(httpServer, {
    cors: {
      origin: (origin, callback) => {
        // Mirror the Express CORS policy: allow any *.vercel.app, ritzyard.com, or no-origin (mobile)
        if (!origin) return callback(null, true);
        if (origin.endsWith('.vercel.app')) return callback(null, true);
        if (origin.includes('ritzyard.com')) return callback(null, true);
        if (
          origin.startsWith('http://localhost:') ||
          origin.startsWith('http://127.0.0.1:')
        ) {
          return callback(null, true);
        }
        return callback(new Error('Socket.IO CORS: origin not allowed'));
      },
      credentials: true,
      methods: ['GET', 'POST'],
    },
    // Reasonable defaults for a small marketplace
    pingTimeout: 30000,
    pingInterval: 25000,
  });

  // ---- Auth middleware ----
  io.use((socket: AuthedSocket, next) => {
    try {
      const auth = (socket.handshake.auth || {}) as Record<string, string>;
      const token = auth.token;
      const buyerToken = auth.buyerToken;
      const email = auth.email;

      // Supplier JWT path
      if (token) {
        const decoded = verifyToken(token);
        if (decoded && (decoded.id || decoded.supplierId)) {
          const supplierId = (decoded.id || decoded.supplierId).toString();
          socket.data.role = 'supplier';
          socket.data.supplierId = supplierId;
          // Auto-join supplier's personal room
          socket.join(`supplier:${supplierId}`);
          return next();
        }
      }

      // Buyer HMAC path -- only valid for joining a specific inquiry room
      if (buyerToken && email && auth.inquiryId) {
        const expected = generateBuyerToken(auth.inquiryId, email);
        if (
          expected.length === buyerToken.length &&
          crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(buyerToken))
        ) {
          socket.data.role = 'buyer';
          socket.data.email = email.toLowerCase();
          socket.join(`inquiry:${auth.inquiryId}`);
          return next();
        }
      }

      // Admin path (optional -- if you have admin tokens)
      if (auth.adminToken) {
        try {
          const decoded = jwt.verify(auth.adminToken, process.env.JWT_SECRET || 'fallback-secret') as any;
          if (decoded && (decoded.type === 'admin' || decoded.role === 'admin')) {
            socket.data.role = 'admin';
            return next();
          }
        } catch {
          // fall through
        }
      }

      return next(new Error('Unauthorized: invalid or missing token'));
    } catch (err: any) {
      return next(new Error('Auth error: ' + (err.message || 'unknown')));
    }
  });

  // ---- Connection handling ----
  io.on('connection', (socket: AuthedSocket) => {
    const role = socket.data.role;
    console.log(`🔌 Socket connected: ${socket.id} (role=${role}, supplier=${socket.data.supplierId || '-'})`);

    // Supplier joins inquiry thread (to read+reply in chat with the buyer)
    socket.on('join_inquiry', (inquiryId: string) => {
      if (!inquiryId || typeof inquiryId !== 'string') return;
      socket.join(`inquiry:${inquiryId}`);
      socket.emit('joined_inquiry', { inquiryId });
    });

    // Buyer joins inquiry thread (auto-joined on auth, but allow re-join for reconnects)
    socket.on('join_inquiry', (inquiryId: string) => {
      if (!inquiryId || typeof inquiryId !== 'string') return;
      // Buyer can only join the inquiry matching their token -- enforced in REST already
      socket.join(`inquiry:${inquiryId}`);
      socket.emit('joined_inquiry', { inquiryId });
    });

    // Typing indicator
    socket.on('typing', (payload: { inquiryId: string; isTyping: boolean }) => {
      if (!payload?.inquiryId) return;
      socket.to(`inquiry:${payload.inquiryId}`).emit('typing', {
        from: role,
        isTyping: !!payload.isTyping,
      });
    });

    // Mark messages as read
    socket.on('mark_read', (payload: { inquiryId: string }) => {
      if (!payload?.inquiryId) return;
      socket.to(`inquiry:${payload.inquiryId}`).emit('messages_read', {
        by: role,
        at: new Date().toISOString(),
      });
    });

    // Disconnect
    socket.on('disconnect', (reason) => {
      console.log(`🔌 Socket disconnected: ${socket.id} (reason=${reason})`);
    });
  });

  console.log('✅ Socket.IO initialized');
  return io;
}

/**
 * Get the initialized IO instance.
 * Returns null if not yet initialized.
 */
export function getIO(): IOServer | null {
  return io;
}

/**
 * Emit a new-lead event to a specific supplier (used by inquiryRoutingService).
 * Safe to call before initSocket -- becomes a no-op in that case.
 */
export function emitNewLead(supplierId: string, payload: {
  leadId: string;
  inquiryNumber: string;
  customerName: string;
  deliveryLocation: string;
  materials: Array<{ materialName: string; quantity: number; unit: string }>;
  matchedCategories: string[];
  score: number;
  estimatedValue?: number;
  whatsappUrl?: string;
  createdAt: string;
}): void {
  if (!io) return; // Socket not initialized -- skip silently
  io.to(`supplier:${supplierId}`).emit('lead:new', payload);
}

/**
 * Emit a new-quote event to the buyer (used when supplier submits a quote).
 * Buyer is identified by the inquiryId (they're already in the inquiry room via HMAC auth).
 */
export function emitNewQuote(inquiryId: string, payload: {
  quoteId: string;
  supplierName: string;
  price: number;
  currency: string;
  pricePerUnit?: number;
  unit?: string;
  validUntil?: string;
  deliveryDays?: number;
  createdAt: string;
}): void {
  if (!io) return;
  io.to(`inquiry:${inquiryId}`).emit('quote:new', payload);
}

/**
 * Emit a chat message in real time to the inquiry room.
 * Called by chatController.sendMessage after saving to DB.
 */
export function emitChatMessage(inquiryId: string, payload: {
  messageId: string;
  senderRole: 'supplier' | 'buyer' | 'admin';
  senderName?: string;
  message: string;
  createdAt: string;
}): void {
  if (!io) return;
  io.to(`inquiry:${inquiryId}`).emit('chat:message', payload);
}

export default {
  initSocket,
  getIO,
  emitNewLead,
  emitNewQuote,
  emitChatMessage,
};
